import { AIDisclaimer } from "@diligentcorp/atlas-react-bundle";
import { useTheme } from "@mui/material";
import type { ReactNode } from "react";

// Spread an Atlas semantic font token (e.g. tokens.semantic.font.label.xs)
// into MUI sx properties. Optional `weight` override (e.g.
// tokens.semantic.fontWeight.emphasis.value for 600).
type FontToken = {
  fontFamily: { value: string };
  fontSize: { value: string };
  fontWeight: { value: number };
  lineHeight: { value: string };
  letterSpacing: { value: string };
};
const textSx = (t: FontToken, weight?: number) => ({
  fontFamily: t.fontFamily.value,
  fontSize: t.fontSize.value,
  fontWeight: weight ?? t.fontWeight.value,
  lineHeight: t.lineHeight.value,
  letterSpacing: t.letterSpacing.value,
});

/**
 * AI "generated/curated by" badge — star icon + caption.
 * Typography: semantic font.label.xs. Star + text color: semantic color.type.muted.
 * Default label is Atlas's "Generated by AI"; pass children to override
 * (e.g. "Curated and summarised by AI").
 */
export function AiBadge({ children }: { children?: ReactNode }) {
  const {
    tokens: {
      semantic: { color, font },
    },
  } = useTheme();
  return (
    <AIDisclaimer
      variant="badge"
      slotProps={{
        root: { sx: { color: color.type.muted.value } },
        text: {
          sx: {
            ...textSx(font.label.xs),
            color: color.type.muted.value,
          },
        },
      }}
    >
      {children}
    </AIDisclaimer>
  );
}

/**
 * AI inaccuracy disclaimer footer — "AI-generated content may have inaccuracies. Learn more".
 * Body: semantic font.label.xs / color.type.muted.
 * Learn more link: semantic color.action.link.default with fontWeight.emphasis.
 */
export function AiInaccuracyDisclaimer({ href = "#" }: { href?: string }) {
  const {
    tokens: {
      semantic: { color, font, fontWeight },
    },
  } = useTheme();
  return (
    <AIDisclaimer
      variant="disclosure"
      learnMore={{ href }}
      slotProps={{
        text: {
          sx: {
            ...textSx(font.label.xs),
            color: color.type.muted.value,
            "& a": {
              color: color.action.link.default.value,
              fontWeight: fontWeight.emphasis.value,
            },
          },
        },
      }}
    />
  );
}
